name: Main Workflow
on: workflow_dispatch
jobs:  
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run:  echo Hello GH Actions!
      - name: Print few lines
        run: |
          echo first line!e
          echo second line!
        
  
